services:
  nginx:
    ports:
      - "80:80"
      - "8888:8888"
    # volumes:
    #   - ./.backend_data:/backend_data
    # profiles:
    #   - disabled

  backend:
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    # profiles:
    #   - disabled

  # disable cloudflare for dev environment
  cloudflare_tunnel:
    profiles:
      - disabled

  standalone:
    ports:
      - "19530:19530"


  attu:
    ports:
      - 3000:3000

  database:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"