from typing import List, Optional, Union

from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
from pydantic import Field, model_validator, validate_call

from .base_llm import BaseLLM


class BaseAiAgent(BaseLLM):

    agent_prompt: str = Field(
        default="",
        description="Prompt template for the agent. If not provided, a default prompt will be used.",
    )
    tools: Optional[List[object]] = Field(
        default_factory=list, description="List of tools that the agent can use."
    )
    agent_verbose: bool = Field(
        default=False,
        description="Whether to enable verbose logging for the agent's actions.",
    )

    @model_validator(mode="after")
    def __after_init(self):
        self._prompt = ChatPromptTemplate.from_messages(
            [
                ("system", self.agent_prompt),
                MessagesPlaceholder(
                    variable_name="chat_history"
                ),  # Để duy trì lịch sử trò chuyện
                ("human", "{input}"),  # Đầu vào hiện tại của người dùng
                MessagesPlaceholder(
                    variable_name="agent_scratchpad"
                ),  # Langchain tự quản lý các bước trung gian
            ]
        )

        self._agent = create_tool_calling_agent(
            llm=self._llm,
            tools=self.tools,
            prompt=self._prompt,
        )

        # 5. Tạo AgentExecutor để chạy agent
        self._agent_executor = AgentExecutor(
            agent=self._agent,
            tools=self.tools,
            verbose=self.agent_verbose,  # Hiển thị các bước hoạt động của agent
        )
        return self

    @validate_call
    def run(
        self, user_input: str, chat_history: Optional[List[BaseMessage]] = None
    ) -> Union[str, List[BaseMessage]]:
        """
        run method to process user input and maintain chat history.
        Args:
            user_input (str): The input from the user.
            chat_history (List[BaseMessage]): The history of messages in the chat.
        Returns:
            str: The response generated by the agent.
            List[BaseMessage]: Updated chat history including the new user input and agent response.
        """

        # Call the agent with user input and chat history
        response = self._agent_executor.invoke(
            {"input": user_input, "chat_history": chat_history if chat_history else []}
        )

        # Update chat history with user input and agent response
        if chat_history is not None:
            chat_history.append(HumanMessage(content=user_input))
            chat_history.append(AIMessage(content=response["output"]))

        return response["output"], chat_history
