services:
  nginx:
    build: 
      context: ./nginx
    restart: on-failure:5
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/SSL:/etc/nginx/SSL
      - ./.data/staticfiles:/staticfiles
      - ./.data/media:/media
    networks:
      private-network:
      microservices-network:
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 512MB
        

  backend:
    build: 
      context: ./backend 
    restart: on-failure:5
    volumes:
      - ./backend:/app
      - ./.data:/.data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - USING_REDIS
    depends_on:
      - database
    networks:
      private-network:
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 4GB
        reservations:
          cpus: '2.00'
          memory: 2GB
          # devices:
          #   - driver: nvidia
          #     capabilities: [gpu]


  redis:
    image: redis:latest
    restart: on-failure:5
    networks:
      private-network:
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 512MB


  database:
    image: postgres:latest
    restart: on-failure:5
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.data/database:/var/lib/postgresql/data
    networks:
      private-network:
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 512MB

  cloudflare_tunnel:
    build: 
      context: ./cloudflare_tunnel
    restart: on-failure:5
    environment:
      - TUNNEL_ORIGIN_KEEPALIVE_TIMEOUT=30s
      - TUNNEL_TOKEN
      - NO_AUTOUPDATE
    networks:
      private-network:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512MB
        reservations:
          cpus: '0.25'
          memory: 256MB


networks:
  microservices-network:
    driver: bridge

  private-network:
    driver: bridge
