services:
  nginx:
    ports:
      - "80:80"


  backend:
    command : python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True


  # database:
    # ports:
    #   - "5433:5432"
